# Generated by Django 2.1.2 on 2018-11-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_mail', models.CharField(max_length=50)),
                ('user_birth', models.CharField(max_length=50)),
                ('user_agree', models.CharField(max_length=50)),
                ('c_date', models.DateTimeField()),
            ],
        ),
    ]
