# Generated by Django 2.1.2 on 2018-11-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='user_agree',
        ),
    ]
